# Generated by Django 5.2.8 on 2026-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelrecord",
            name="cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
